services:
    api:
        build: .
        container_name: pixelated-api
        ports:
            - '${PORT:-3001}:${PORT:-3001}' # Defaults to 3001 if not set
        env_file:
            - .env
            - .env.answers
        restart: always
